version: '3.6'

services:
  postgresql:
    container_name: postgresql
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - /var/tmp/react-hasura-auth0-demo/db:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "test `psql -U postgres postgres -c '\\dt' -t | wc -l` = 3"]
      interval: 1s
      timeout: 30s
      retries: 10
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: "Asia/Tokyo"
  hasura:
    container_name: hasura
    image: hasura/graphql-engine:v2.40.2
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgresql:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: hasura
